<?php

// config/advent.php
return [
    'images' => [
        'welcome' => 'AgACAgIAAxkDAAN7aVTYOrW_teY_uC4IfkUxFTXZxEgAAkMMaxvFGKlKTTONyDg1olQBAAMCAAN5AAM4BA',
        'task1_1'    => 'AgACAgIAAxkDAANraVTWHOwJ8jk_3F-rNku5FoybcQIAAh8MaxvFGKlKhHcnf5YoIfEBAAMCAAN3AAM4BA',
        'task1_2'    => 'AgACAgIAAxkDAANsaVTWHginGtXNmcg_pvLlWBYqvpsAAiAMaxvFGKlK28w2uUi_HbYBAAMCAAN3AAM4BA',
        'task1_3'    => 'AgACAgIAAxkDAANtaVTWH8d6byxOH61bITcKNDuBcLUAAiEMaxvFGKlKTrlMOmd8SSoBAAMCAAN3AAM4BA',
        'task2_1'    => 'AgACAgIAAxkDAANuaVTWIPCg6vr1ZmVYLI3hXzmnLokAAiIMaxvFGKlKGyBMcEBr5tMBAAMCAAN4AAM4BA',
        'task2_2'    => 'AgACAgIAAxkDAANvaVTWIhOCT8OUao2zgKAfeDW2NiMAAiMMaxvFGKlKXvbOKh7NgqABAAMCAAN3AAM4BA',
        'task2_3'    => 'AgACAgIAAxkDAANwaVTWIrEFRHCVEaMqEWIfzKfFLO0AAiQMaxvFGKlKr4SVo0FjYJQBAAMCAAN4AAM4BA',
        'task3_1'    => 'AgACAgIAAxkDAANxaVTWI8odmWcFHESaAasFPxsLqnUAAiUMaxvFGKlK7A7EyGDZw5cBAAMCAAN5AAM4BA',
        'task3_2'    => 'AgACAgIAAxkDAANyaVTWI0kgbR4v5sdh8GV85WH0Vs0AAiYMaxvFGKlK0FyloJg4v04BAAMCAAN4AAM4BA',
        'task3_3'    => 'AgACAgIAAxkDAAN8aVTbrjmy-6BbMHrosdHoOHQLhXUAAmUMaxvFGKlK8Ow3mYADxNsBAAMCAAN4AAM4BA',
        'task4_1'    => 'AgACAgIAAxkDAAIFxWlZds1ozdhlPygIMel5AlOhLSMwAAJXDGsbl-HQSiPZXaaep9f1AQADAgADdwADOAQ',
        'task4_2'    => 'AgACAgIAAxkDAAIFxmlZdtEIiUvDDSVBVyZvLRNtnP3WAAJaDGsbl-HQSnIOd1QVDNPwAQADAgADeAADOAQ',
        'task4_3'    => 'AgACAgIAAxkDAAIFx2lZdtO-kSXz-EIWllUlOwwlHf6yAAJbDGsbl-HQSiKrn4ynQ7zEAQADAgADeAADOAQ',
        'task5_1'    => 'AgACAgIAAxkDAAIFyGlZdteASJRdle_8n4rSIlqafWA3AAJdDGsbl-HQSoXjlU1Ed54pAQADAgADeAADOAQ',
        'task5_2'    => 'AgACAgIAAxkDAAIFyWlZdt7xLoUI-VxDRKvfkxqBwMc_AAJeDGsbl-HQSuTC4llsDT01AQADAgADeQADOAQ',
        'task5_3'    => 'AgACAgIAAxkDAAIFymlZduFQiolhXhwnQQZiqlYOOxENAAJfDGsbl-HQSswWpDZ_7iW0AQADAgADeAADOAQ',
        'task6_1'    => 'AgACAgIAAxkDAAIFy2lZduXu8pXlAkJg_cwWMA7tguu4AAJgDGsbl-HQSkckxWn2BHM4AQADAgADeQADOAQ',
        'task6_2'    => 'AgACAgIAAxkDAAIFzGlZdudUFUdnyuUx7dYeGeyz01vnAAJhDGsbl-HQStPFvK3KU8X_AQADAgADeAADOAQ',
        'task6_3'    => 'AgACAgIAAxkDAAIFzWlZdu1JTmxpeNKUu9kCJvEaUQYVAAJjDGsbl-HQSi_1QYatKVbFAQADAgADeQADOAQ',
        'task7_1'    => 'AgACAgIAAxkDAAILcGldXVb-7BjfgyDYQnoncVkgQPzEAAISFWsbEjXoSvKww3OAoMalAQADAgADeAADOAQ',
        'task7_2'    => 'AgACAgIAAxkDAAILcWldXVmHSV5bll8nFc0x0SH180r1AAITFWsbEjXoSh8twBqPk4MZAQADAgADeQADOAQ',
        'task7_3'    => 'AgACAgIAAxkDAAILcmldXVucMhxaRWcjPY1RK4_kR7kdAAIUFWsbEjXoSlIhG7NHbc01AQADAgADeAADOAQ',
        'task8_1'    => 'AgACAgIAAxkDAAILc2ldXV3R71c6LOL85IQhvd0Xb_C_AAIVFWsbEjXoSs7UlxQoX_pJAQADAgADeQADOAQ',
        'task8_2'    => 'AgACAgIAAxkDAAILdGldXV-hZaMBeUebQbKVK5uMz5jzAAIWFWsbEjXoSkwmM8ibGc-1AQADAgADeAADOAQ',
        'task8_3'    => 'AgACAgIAAxkDAAILdWldXWRtCVco2j8yTiTfJ3hsfnX5AAIXFWsbEjXoShtsrW5IzD-eAQADAgADdwADOAQ',
        'task9_1'    => 'AgACAgIAAxkDAAILdmldXWX7NMhwCHC4xwABXz3ZL_PQ2gACGBVrGxI16EpOyb-CHhm_oQEAAwIAA3kAAzgE',
        'task9_2'    => 'AgACAgIAAxkDAAILd2ldXWd0Ch8Qdd_q88DkG2HqsxqDAAIZFWsbEjXoSvAnw8U3F8ckAQADAgADeQADOAQ',
        'task9_3'    => 'AgACAgIAAxkDAAILeGldXWm4gyHWOry40F-sP06bnMn6AAIaFWsbEjXoSjpbzmCK77U2AQADAgADeAADOAQ',
        'task10_1'    => 'AgACAgIAAxkDAAILeWldXWtpO0w2Ocx7ZOEzsrCFYTsUAAIbFWsbEjXoSlL5Rn1Q3quKAQADAgADeAADOAQ',
        'task10_2'    => 'AgACAgIAAxkDAAILemldXXP7ix-_0pgnYqHQuIwpFhQaAAIcFWsbEjXoSvaWxwaaUJ4OAQADAgADdwADOAQ',
        'task10_3'    => 'AgACAgIAAxkDAAILe2ldXXUjTC3N2uSKWkHXyJ75HglFAAIdFWsbEjXoSlxYc9NfiU7MAQADAgADeAADOAQ',
        'task11_1'    => '',
        'task11_2'    => '',
        'task11_3'    => '',
    ]
];